firewalls:
  main:
    pattern: "^/"
    auth:
      cookie:
        name: "SESSION_ID"

access:
  - path: /login
    require: IS_AUTHENTICATED_ANONYMOUSLY

  - path: /logout
    require: IS_AUTHENTICATED_ANONYMOUSLY

  - path: /static*
    require: IS_AUTHENTICATED_ANONYMOUSLY

  - path: /
    require: AUTH_REQUIRED

session:
  cookie: "SESSION_ID"
  cookie_path: "/"
  expires: 0
  secure: false

csrf:
  enabled: false
  secret: "your-32-byte-auth-key-here!!!!"
  secure: true
  same_site: "Lax"
  field_name: "csrf.token"
  header_name: "X-CSRF-Token"

logout:
  enabled: true
  logout_url: "/logout"
  delete_cookies: ["SESSION_ID"]
  redirect_url: "/login"

entry_point:
  login_url: "/login"
  code: 302